# Generated by Django 5.2.7 on 2025-10-28 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='total',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=12),
        ),
    ]
