# Generated by Django 5.2.7 on 2025-10-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_total_price_alter_revenue_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
