# Generated by Django 5.2.7 on 2025-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', 'Chưa giao hàng'), ('delivering', 'Đang giao hàng'), ('delivered', 'Đã giao hàng')], default='not_delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
