# Generated by Django 5.2.7 on 2025-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_delivery_end_order_delivery_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
